### ISSUE TITLE
index.html doesn't load correctly.

### ISSUE THREAD

**Issue by ghost** [pinceladasdaweb/Vimeo-Carousel-Gallery#1]
On line 12:
'script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'

I added 'http:' to make it work, you might have forgotten to add it. Thanks for the code.

**Comment by pinceladasdaweb** [comment]
No, I have not forgotten. I prefer to leave without it so the protocol is defined as the URL where it is running, either http or https.

**Comment by ghost** [comment]
Do I need to add http/https or is it supposed to be automatically filled in? It wasn't working before I added the protocol.

**Comment by pinceladasdaweb** [comment]
If you access the local file, it adds the file protocol :. If you access through a server, the protocol is http or https.
